version: '3'

services:
  db:
    container_name: invoicedb
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
    - ./.mysql.env
    environment:
      MYSQL_DATABASE: invoice
      MYSQL_USER: backend
    volumes:
      - ./data:/var/lib/mysql